# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participer', '0004_equipe_inscrit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='inscrit',
            field=models.NullBooleanField(),
        ),
    ]
